spring.application.name=vehicle-service-api
# ???????????? ?? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_service_db
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ???????????? ??????????? ?? Hardhat
web3j.client-address=http://127.0.0.1:8545

# ?????????? ???????? (??? Relayer)
# ?????????? Private Key Account #0 ? ????????? Hardhat
blockchain.admin-private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
blockchain.contract-address=0x????_??????_?_IGNITION